version: '3.7'
services:
  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - '9000:9000'
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data
    volumes:
      - minio-data:/data

  airflow:
    build:
      context: ./airflow
      dockerfile: Dockerfile
    container_name: airflow
    depends_on:
      - minio
      - trino
    ports:
      - '8080:8080'
    environment:
      - AIRFLOW__CORE__EXECUTOR=SequentialExecutor
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW__LOGGING__LOGGING_LEVEL=INFO
      - KAGGLE_CONFIG_DIR=/opt/airflow/.kaggle
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/scripts:/opt/airflow/scripts
      - ./kaggle.json:/opt/airflow/.kaggle/kaggle.json:ro
      - airflow-logs:/opt/airflow/logs
    command: >
      bash -c "airflow db init && \
               airflow scheduler & \
               airflow webserver"

  trino:
    image: trinodb/trino:latest
    container_name: trino
    ports:
      - '8082:8080'
    volumes:
      - ./trino/etc/catalog:/etc/trino/catalog:ro
    depends_on:
      - minio

volumes:
  minio-data:
  airflow-logs: